// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJauzLwW_7qhDneHNOJWSCtgFks7DBkRA',
    appId: '1:441491189536:web:47d40017bdf90f8e9e7145',
    messagingSenderId: '441491189536',
    projectId: 'pregnancyapp-f8332',
    authDomain: 'pregnancyapp-f8332.firebaseapp.com',
    storageBucket: 'pregnancyapp-f8332.firebasestorage.app',
    measurementId: 'G-L1DWPD0VP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutrSbIfDkNgBWaLvc-S0kPgfMJN3-Gy4',
    appId: '1:441491189536:android:f168ffd7a6ca551e9e7145',
    messagingSenderId: '441491189536',
    projectId: 'pregnancyapp-f8332',
    storageBucket: 'pregnancyapp-f8332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNrcWLCSJ8nqhMbahV3XvYVXLtgmEChI',
    appId: '1:441491189536:ios:fbc89c6b228474649e7145',
    messagingSenderId: '441491189536',
    projectId: 'pregnancyapp-f8332',
    storageBucket: 'pregnancyapp-f8332.firebasestorage.app',
    iosBundleId: 'com.example.pregnancyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNrcWLCSJ8nqhMbahV3XvYVXLtgmEChI',
    appId: '1:441491189536:ios:fbc89c6b228474649e7145',
    messagingSenderId: '441491189536',
    projectId: 'pregnancyapp-f8332',
    storageBucket: 'pregnancyapp-f8332.firebasestorage.app',
    iosBundleId: 'com.example.pregnancyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJauzLwW_7qhDneHNOJWSCtgFks7DBkRA',
    appId: '1:441491189536:web:49e7ba898396d7aa9e7145',
    messagingSenderId: '441491189536',
    projectId: 'pregnancyapp-f8332',
    authDomain: 'pregnancyapp-f8332.firebaseapp.com',
    storageBucket: 'pregnancyapp-f8332.firebasestorage.app',
    measurementId: 'G-NYKEHLJ95R',
  );
}
